/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2263;

public class App {


    public static void main(String[] args) {
        Graph graph = new Graph();
        graph.print();
        graph.summary();

}}
